version: '2'
services:
  db:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "Anzen1.2.3."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" # for debug. Remove this for production

